# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: '.NET Core - Restore packages'
  inputs:
    command: 'restore'
    projects: './src'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: '.NET Core - Build'
  inputs:
    command: 'build'
    projects: './src'
    arguments: '-c $(buildConfiguration) --no-restore'

- script: |
    dotnet tool install dotnet-reportgenerator-globaltool --tool-path .
    mkdir $(Build.SourcesDirectory)\results 

    dotnet test .\src\JpProject.PasswordHasher.sln --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura  PasswordHasher.Test
    dotnet test .\src\JpProject.PasswordHasher.sln --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:MergeWtih=$(Build.SourcesDirectory)\src\PasswordHasher.Test\coverage.cobertura.xml PasswordHasherRepository.Test
    copy $(Build.SourcesDirectory)\src\PasswordHasher.Test\coverage.cobertura.xml $(Build.SourcesDirectory)\results
    reportgenerator "-reports:$(Build.SourcesDirectory)\src\PasswordHasherRepository.Test\coverage.cobertura.xml" "-targetdir:results" "-reporttypes:HTMLInline;HTMLChart"
  displayName: '.NET Core - Run Tests'

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishCodeCoverageResults@1
  inputs:
    summaryFileLocation: $(Build.SourcesDirectory)\results\coverage.cobertura.xml
    reportDirectory: $(Build.SourcesDirectory)\results
    codecoverageTool: cobertura

